-- ============================================================
-- GreenStep Challenge Admin -- Refined Schema
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

-- Categories
create table if not exists categories (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  description text
);

-- Departments / Groups
create table if not exists departments (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  description text,
  "createdBy" bigint, -- Circular reference handled after users table
  "createdAt" timestamptz not null default now()
);

-- Users
create table if not exists users (
  id            bigint generated by default as identity primary key,
  "firstName"   text not null,
  "lastName"    text not null,
  email         text not null unique,
  username      text not null unique,
  "passwordHash" text not null,
  role          text not null default 'GeneralUser'
                  check (role in ('SuperAdmin', 'Admin', 'GeneralUser')),
  status        text not null default 'Active'
                  check (status in ('Active', 'Deactivated')),
  "groupId"     bigint references departments(id) on delete set null,
  "dateJoined"  date not null default current_date,
  "lastActive"  timestamptz
);

-- Add foreign key to departments now that users table exists
alter table departments add foreign key ("createdBy") references users(id) on delete set null;

-- Actions
create table if not exists actions (
  id            bigint generated by default as identity primary key,
  "categoryId"  bigint not null references categories(id) on delete restrict,
  name          text not null,
  description   text,
  points        integer not null default 1 check (points > 0)
);

-- Themes
create table if not exists themes (
  id            bigint generated by default as identity primary key,
  name          text not null unique,
  description   text,
  "bgColorHeader"  varchar(7),
  "txColorHeader" varchar(7),
  "bgColorBody"  varchar(7),
  "txColorBody" varchar(7),
  "createdBy"   bigint references users(id) on delete set null,
  "createdAt"   timestamptz not null default now()
);

-- Templates
create table if not exists templates (
  id            bigint generated by default as identity primary key,
  name          text not null,
  description   text,
  "categoryId"  bigint not null references categories(id) on delete restrict,
  "themeId"     bigint not null references themes(id) on delete restrict,
  "createdBy"   bigint references users(id) on delete set null,
  "createdAt"   timestamptz not null default now()
);

-- Challenges
create table if not exists challenges (
  id                bigint generated by default as identity primary key,
  name              text not null,
  description       text,
  "categoryId"      bigint not null references categories(id) on delete restrict,
  "themeId"         bigint not null references themes(id) on delete restrict,
  "startDate"       date not null,
  "endDate"         date not null,
  "startTime"       time,
  "endTime"         time,
  status            text not null default 'Upcoming'
                      check (status in ('Active', 'Upcoming', 'Completed', 'Archived')),
  "createdBy"       bigint references users(id) on delete set null,
  "participantCount" integer not null default 0,
  "createdAt"       timestamptz not null default now(),
  constraint valid_date_range check ("endDate" >= "startDate")
);

-- Participation (action completions)
create table if not exists participation (
  id            bigint generated by default as identity primary key,
  "userId"      bigint not null references users(id) on delete cascade,
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "actionId"    bigint not null references actions(id) on delete cascade,
  "completedAt" date not null default current_date,
  notes         text,
  "photoUrl"    text
);

-- Activity Logs
create table if not exists activity_logs (
  id            bigint generated by default as identity primary key,
  "userId"      bigint not null references users(id) on delete cascade,
  "actionType"  text not null,
  timestamp     timestamptz not null default now(),
  details       text
);

-- Reports
create table if not exists reports (
  id            bigint generated by default as identity primary key,
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "generatedBy" bigint references users(id) on delete set null,
  "generatedAt" timestamptz not null default now(),
  title         text,
  filters       jsonb,
  "fileUrl"     text
);

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists idx_users_email on users(email);
create index if not exists idx_users_username on users(username);
create index if not exists idx_users_group on users("groupId");

create index if not exists idx_challenges_status on challenges(status);
create index if not exists idx_challenges_category on challenges("categoryId");
create index if not exists idx_challenges_dates on challenges("startDate", "endDate");

create index if not exists idx_actions_category on actions("categoryId");

create index if not exists idx_participation_user on participation("userId");
create index if not exists idx_participation_challenge on participation("challengeId");
create index if not exists idx_participation_action on participation("actionId");

create index if not exists idx_activity_logs_timestamp on activity_logs(timestamp);

create index if not exists idx_reports_challenge on reports("challengeId");