-- ============================================================
-- GreenStep Challenge Admin -- Initial Schema
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

-- Departments / Participant Groups
create table if not exists departments (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  "createdAt" date not null default current_date
);

-- Users
create table if not exists users (
  id           bigint generated by default as identity primary key,
  name         text not null,
  email        text not null unique,
  role         text not null default 'GeneralUser'
                 check (role in ('SuperAdmin', 'Admin', 'GeneralUser')),
  status       text not null default 'Active'
                 check (status in ('Active', 'Deactivated')),
  "groupId"    bigint references departments(id) on delete set null,
  department   text,
  "createdAt"  date not null default current_date,
  "lastActive" date
);

-- Actions (standalone, no challenge link)
create table if not exists actions (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  category    text not null,
  points      integer not null default 0
);

-- Challenges
create table if not exists challenges (
  id                 bigint generated by default as identity primary key,
  name               text not null,
  description        text,
  category           text,
  theme              text default '#4CAF50',
  "startDate"        date,
  "endDate"          date,
  "joinBy"           date,
  status             text not null default 'Upcoming'
                       check (status in ('Active', 'Upcoming', 'Completed', 'Archived')),
  "createdBy"        bigint references users(id) on delete set null,
  "participantCount" integer not null default 0,
  "groupId"          bigint references departments(id) on delete set null
);

-- Challenge <-> Actions (many-to-many)
create table if not exists challenge_actions (
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "actionId"    bigint not null references actions(id) on delete cascade,
  primary key ("challengeId", "actionId")
);

-- Challenge <-> Participants (many-to-many)
create table if not exists challenge_participants (
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "userId"      bigint not null references users(id) on delete cascade,
  primary key ("challengeId", "userId")
);

-- Templates
create table if not exists templates (
  id                 bigint generated by default as identity primary key,
  name               text not null,
  description        text,
  type               text,
  category           text,
  theme              text default '#4CAF50',
  "createdBy"        bigint references users(id) on delete set null,
  "createdAt"        date not null default current_date,
  "joinBy"           date,
  "participantGroup" bigint references departments(id) on delete set null
);

-- Presets
create table if not exists presets (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  category    text,
  theme       text default '#4CAF50',
  status      text default 'Upcoming',
  "createdAt" date not null default current_date
);

-- Preset Actions (embedded in preset)
create table if not exists preset_actions (
  id          bigint generated by default as identity primary key,
  "presetId"  bigint not null references presets(id) on delete cascade,
  name        text not null,
  description text,
  category    text,
  points      integer not null default 0
);

-- Participation (user action completions)
create table if not exists participation (
  id            bigint generated by default as identity primary key,
  "userId"      bigint not null references users(id) on delete cascade,
  "challengeId" bigint not null references challenges(id) on delete cascade,
  "actionId"    bigint not null references actions(id) on delete cascade,
  "completedAt" date not null,
  notes         text,
  "photoUrl"    text
);

-- Activity Logs (admin audit trail)
create table if not exists activity_logs (
  id        bigint generated by default as identity primary key,
  "userId"  bigint references users(id) on delete set null,
  action    text not null,
  timestamp timestamptz not null default now(),
  details   text
);

-- Indexes
create index if not exists idx_users_group on users("groupId");
create index if not exists idx_users_email on users(email);
create index if not exists idx_challenges_status on challenges(status);
create index if not exists idx_challenges_group on challenges("groupId");
create index if not exists idx_participation_user on participation("userId");
create index if not exists idx_participation_challenge on participation("challengeId");
create index if not exists idx_participation_action on participation("actionId");
create index if not exists idx_activity_logs_user on activity_logs("userId");
